/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.Controleur;
import Modele.Panier;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author vn934281
 */
public class VueGraphique extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form VueGraphique
     */
    public VueGraphique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plus = new javax.swing.JButton();
        texte = new javax.swing.JLabel();
        moins = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        plus.setText("+");
        plus.setName("plus"); // NOI18N
        getContentPane().add(plus);

        texte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte.setText("0");
        getContentPane().add(texte);

        moins.setText("-");
        moins.setName("moins"); // NOI18N
        moins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moinsActionPerformed(evt);
            }
        });
        getContentPane().add(moins);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moinsActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton moins;
    private javax.swing.JButton plus;
    private javax.swing.JLabel texte;
    // End of variables declaration//GEN-END:variables

    public void addControleur(Controleur c)
    {
        plus.addActionListener(c);
        moins.addActionListener(c);
    }
    
    
    @Override
    public void update(Observable o, Object arg) {
        Panier p = (Panier)o;
        texte.setText("Nombre de fruits " + p.getSize());
    }
   
}
